export const FETCH_PLACES = "FETCH_PLACES";
export const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export const PLACE_SELECTED = "PLACE_SELECTED";
export const ADD_RATINGS = "ADD_RATINGS";
export const SET_CURRENT_PLACE = "SET_CURRENT_PLACE";
export const ADD_OR_UPDATE_PLACE = "ADD_OR_UPDATE_PLACE";
export const FETCH_RATINGS = "FETCH_RATINGS";